package org.informea.odata.producer.toolkit.impl;

// Generated Mar 29, 2012 4:48:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.informea.odata.pojo.AbstractPebldsCountry;
import org.odata4j.core.OEntities;
import org.odata4j.core.OEntity;
import org.odata4j.core.OEntityKey;
import org.odata4j.core.OLink;
import org.odata4j.core.OProperties;
import org.odata4j.core.OProperty;
import org.odata4j.edm.EdmEntitySet;

/**
 * PebldsCountry generated by hbm2java
 */
@Entity
@Table(name = "peblds_country", uniqueConstraints = {
		@UniqueConstraint(columnNames = "code2l"),
		@UniqueConstraint(columnNames = "code"),
		@UniqueConstraint(columnNames = "name") })
public class PebldsCountry extends AbstractPebldsCountry implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
	private Short id;
    @Column(name = "code", unique = true, nullable = false, length = 3)
    @NotNull
    @Length(max = 3)
	private String code;
    @Column(name = "code2l", unique = true, length = 2)
    @Length(max = 2)
	private String code2l;
    @Column(name = "name", unique = true, nullable = false, length = 64)
    @NotNull
    @Length(max = 64)
	private String name;
    @Column(name = "icon_large")
	private String iconLarge;
    @Column(name = "icon_small", nullable = false)
    @NotNull
	private String iconSmall;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rec_created", nullable = false, length = 19)
    @NotNull
	private Date recCreated;
    @Column(name = "rec_author", nullable = false, length = 32)
    @NotNull
    @Length(max = 32)
	private String recAuthor;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pebldsCountry")
	private Set<PebldsBestPractice> pebldsBestPractices = new HashSet<PebldsBestPractice>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pebldsCountry")
	private Set<PebldsTechnicalReport> pebldsTechnicalReports = new HashSet<PebldsTechnicalReport>(0);
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "peblds_project_country", joinColumns = { @JoinColumn(name = "id_country", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_project", nullable = false, updatable = false) })
	private Set<PebldsProject> pebldsProjects = new HashSet<PebldsProject>(0);

	public PebldsCountry() {
	}

	public PebldsCountry(String code, String name, String iconSmall,
			Date recCreated, String recAuthor) {
		this.code = code;
		this.name = name;
		this.iconSmall = iconSmall;
		this.recCreated = recCreated;
		this.recAuthor = recAuthor;
	}

	public PebldsCountry(String code, String code2l, String name,
			String iconLarge, String iconSmall, Date recCreated,
			String recAuthor, Set<PebldsBestPractice> pebldsBestPractices,
			Set<PebldsTechnicalReport> pebldsTechnicalReports,
			Set<PebldsProject> pebldsProjects) {
		this.code = code;
		this.code2l = code2l;
		this.name = name;
		this.iconLarge = iconLarge;
		this.iconSmall = iconSmall;
		this.recCreated = recCreated;
		this.recAuthor = recAuthor;
		this.pebldsBestPractices = pebldsBestPractices;
		this.pebldsTechnicalReports = pebldsTechnicalReports;
		this.pebldsProjects = pebldsProjects;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCode2l() {
		return this.code2l;
	}

	public void setCode2l(String code2l) {
		this.code2l = code2l;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIconLarge() {
		return this.iconLarge;
	}

	public void setIconLarge(String iconLarge) {
		this.iconLarge = iconLarge;
	}

	public String getIconSmall() {
		return this.iconSmall;
	}

	public void setIconSmall(String iconSmall) {
		this.iconSmall = iconSmall;
	}

	public Date getRecCreated() {
		return this.recCreated;
	}

	public void setRecCreated(Date recCreated) {
		this.recCreated = recCreated;
	}

	public String getRecAuthor() {
		return this.recAuthor;
	}

	public void setRecAuthor(String recAuthor) {
		this.recAuthor = recAuthor;
	}

	public Set<PebldsBestPractice> getPebldsBestPractices() {
		return this.pebldsBestPractices;
	}

	public void setPebldsBestPractices(
			Set<PebldsBestPractice> pebldsBestPractices) {
		this.pebldsBestPractices = pebldsBestPractices;
	}

	public Set<PebldsTechnicalReport> getPebldsTechnicalReports() {
		return this.pebldsTechnicalReports;
	}

	public void setPebldsTechnicalReports(
			Set<PebldsTechnicalReport> pebldsTechnicalReports) {
		this.pebldsTechnicalReports = pebldsTechnicalReports;
	}

	public Set<PebldsProject> getPebldsProjects() {
		return this.pebldsProjects;
	}

	public void setPebldsProjects(Set<PebldsProject> pebldsProjects) {
		this.pebldsProjects = pebldsProjects;
	}

	@Override
    public OEntity asEntity(EdmEntitySet ees){
        final List<OProperty<?>> properties = new ArrayList<OProperty<?>>();
        properties.add(OProperties.int16("id", getId()));
        properties.add(OProperties.string("code", getCode()));
        properties.add(OProperties.string("code2l", getCode2l()));
        properties.add(OProperties.string("name", getName()));
        return OEntities.create(ees, OEntityKey.create(getId()), properties, new ArrayList<OLink>(), null, null);
    }
}
