package org.informea.odata.producer.toolkit.impl;

// Generated Mar 29, 2012 4:26:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.informea.odata.pojo.AbstractPebldsBestPractice;
import org.odata4j.core.OEntities;
import org.odata4j.core.OEntity;
import org.odata4j.core.OEntityKey;
import org.odata4j.core.OLink;
import org.odata4j.core.OProperties;
import org.odata4j.core.OProperty;
import org.odata4j.edm.EdmEntitySet;

/**
 * PebldsBestPractice generated by hbm2java
 */
@Entity
@Table(name = "peblds_best_practice")
public class PebldsBestPractice extends AbstractPebldsBestPractice implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
	private Integer id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_topic")
	private PebldsTopic pebldsTopic;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_country")
	private PebldsCountry pebldsCountry;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_treaty")
	private PebldsTreaty pebldsTreaty;
    @Column(name = "title", nullable = false, length = 128)
    @NotNull
    @Length(max = 128)
	private String title;
    @Column(name = "content", length = 65535)
    @Length(max = 65535)
	private String content;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "submitted", length = 19)
	private Date submitted;
    @Column(name = "contact", length = 64)
    @Length(max = 64)
	private String contact;
    @Column(name = "contact_details")
	private String contactDetails;
    @Column(name = "rec_author", nullable = false, length = 32)
    @NotNull
    @Length(max = 32)
	private String recAuthor;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rec_created", nullable = false, length = 19)
    @NotNull
	private Date recCreated;
    @JoinTable(name = "peblds_best_practice_wpfb_files", joinColumns = {
            @JoinColumn(name = "id_best_practice", nullable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "id_wpfb_files", nullable = false)})
    @ManyToMany(fetch = FetchType.LAZY)
    private Set<PebldsWpfbFiles> pebldsWpfbFiles;


	public PebldsBestPractice() {
	}

	public PebldsBestPractice(String title, String recAuthor, Date recCreated) {
		this.title = title;
		this.recAuthor = recAuthor;
		this.recCreated = recCreated;
	}

	public PebldsBestPractice(PebldsTopic pebldsTopic,
			PebldsCountry pebldsCountry, PebldsTreaty pebldsTreaty,
			String title, String content, Date submitted, String contact,
			String contactDetails, String recAuthor, Date recCreated) {
		this.pebldsTopic = pebldsTopic;
		this.pebldsCountry = pebldsCountry;
		this.pebldsTreaty = pebldsTreaty;
		this.title = title;
		this.content = content;
		this.submitted = submitted;
		this.contact = contact;
		this.contactDetails = contactDetails;
		this.recAuthor = recAuthor;
		this.recCreated = recCreated;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PebldsTopic getPebldsTopic() {
		return this.pebldsTopic;
	}

	public void setPebldsTopic(PebldsTopic pebldsTopic) {
		this.pebldsTopic = pebldsTopic;
	}

	public PebldsCountry getPebldsCountry() {
		return this.pebldsCountry;
	}

	public void setPebldsCountry(PebldsCountry pebldsCountry) {
		this.pebldsCountry = pebldsCountry;
	}

	public PebldsTreaty getPebldsTreaty() {
		return this.pebldsTreaty;
	}

	public void setPebldsTreaty(PebldsTreaty pebldsTreaty) {
		this.pebldsTreaty = pebldsTreaty;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSubmitted() {
		return this.submitted;
	}

	public void setSubmitted(Date submitted) {
		this.submitted = submitted;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContactDetails() {
		return this.contactDetails;
	}

	public void setContactDetails(String contactDetails) {
		this.contactDetails = contactDetails;
	}

	public String getRecAuthor() {
		return this.recAuthor;
	}

	public void setRecAuthor(String recAuthor) {
		this.recAuthor = recAuthor;
	}

	public Date getRecCreated() {
		return this.recCreated;
	}

	public void setRecCreated(Date recCreated) {
		this.recCreated = recCreated;
	}

    public Set<PebldsWpfbFiles> getPebldsWpfbFiles()
    {
        return pebldsWpfbFiles;
    }

    public void setPebldsWpfbFiles(Set<PebldsWpfbFiles> pebldsWpfbFiles)
    {
        this.pebldsWpfbFiles = pebldsWpfbFiles;
    }

    @Override
    public OEntity asEntity(EdmEntitySet ees) {
        final List<OProperty<?>> properties = new ArrayList<OProperty<?>>();
        properties.add(OProperties.int32("id", getId()));
        properties.add(OProperties.string("country", getPebldsCountry().getCode()));
        properties.add(OProperties.int32("id_topic", getPebldsTopic().getId()));
        properties.add(OProperties.string("treaty", getPebldsTreaty().getOdataName()));
        properties.add(OProperties.string("title", getTitle()));
        properties.add(OProperties.string("content", getContent()));
        properties.add(OProperties.datetime("submitted", getSubmitted()));
        properties.add(OProperties.string("contact", getContact()));
        properties.add(OProperties.string("contactDetails", getContactDetails()));

        return OEntities.create(ees, OEntityKey.create(getId()), properties, new ArrayList<OLink>(), null, null);
    }
}
