package org.informea.odata.producer.toolkit.impl;

// Generated Mar 29, 2012 4:48:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.informea.odata.pojo.AbstractPebldsTechnicalReport;
import org.odata4j.core.OEntities;
import org.odata4j.core.OEntity;
import org.odata4j.core.OEntityKey;
import org.odata4j.core.OLink;
import org.odata4j.core.OProperties;
import org.odata4j.core.OProperty;
import org.odata4j.edm.EdmEntitySet;

/**
 * PebldsTechnicalReport generated by hbm2java
 */
@Entity
@Table(name = "peblds_technical_report")
public class PebldsTechnicalReport extends AbstractPebldsTechnicalReport implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
	private Integer id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_country")
	private PebldsCountry pebldsCountry;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_treaty")
	private PebldsTreaty pebldsTreaty;
    @Column(name = "title", nullable = false, length = 128)
    @NotNull
    @Length(max = 128)
	private String title;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "submitted", length = 19)
	private Date submitted;
    @Column(name = "rec_author", nullable = false, length = 32)
    @NotNull
    @Length(max = 32)
	private String recAuthor;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rec_created", nullable = false, length = 19)
    @NotNull
	private Date recDate;
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "peblds_technical_report_topic",
        joinColumns = { @JoinColumn(name = "id_technical_report", nullable = false, updatable = false) },
        inverseJoinColumns = { @JoinColumn(name = "id_topic", nullable = false, updatable = false) })
	private Set<PebldsTopic> pebldsTopics = new HashSet<PebldsTopic>(0);
    @JoinTable(name = "peblds_technical_report_wpfb_files", joinColumns = {
            @JoinColumn(name = "id_technical_report", nullable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "id_wpfb_files", nullable = false)})
    @ManyToMany(fetch = FetchType.LAZY)
    private Set<PebldsWpfbFiles> pebldsWpfbFiles;

	public PebldsTechnicalReport() {
	}

	public PebldsTechnicalReport(String title, String recAuthor, Date recDate) {
		this.title = title;
		this.recAuthor = recAuthor;
		this.recDate = recDate;
	}

	public PebldsTechnicalReport(PebldsCountry pebldsCountry,
			PebldsTreaty pebldsTreaty, String title, Date submitted,
			String recAuthor, Date recDate, Set<PebldsTopic> pebldsTopics) {
		this.pebldsCountry = pebldsCountry;
		this.pebldsTreaty = pebldsTreaty;
		this.title = title;
		this.submitted = submitted;
		this.recAuthor = recAuthor;
		this.recDate = recDate;
		this.pebldsTopics = pebldsTopics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PebldsCountry getPebldsCountry() {
		return this.pebldsCountry;
	}

	public void setPebldsCountry(PebldsCountry pebldsCountry) {
		this.pebldsCountry = pebldsCountry;
	}

	public PebldsTreaty getPebldsTreaty() {
		return this.pebldsTreaty;
	}

	public void setPebldsTreaty(PebldsTreaty pebldsTreaty) {
		this.pebldsTreaty = pebldsTreaty;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getSubmitted() {
		return this.submitted;
	}

	public void setSubmitted(Date submitted) {
		this.submitted = submitted;
	}

	public String getRecAuthor() {
		return this.recAuthor;
	}

	public void setRecAuthor(String recAuthor) {
		this.recAuthor = recAuthor;
	}

	public Date getRecDate() {
		return this.recDate;
	}

	public void setRecDate(Date recDate) {
		this.recDate = recDate;
	}

	public Set<PebldsTopic> getPebldsTopics() {
		return this.pebldsTopics;
	}

	public void setPebldsTopics(Set<PebldsTopic> pebldsTopics) {
		this.pebldsTopics = pebldsTopics;
	}

    public Set<PebldsWpfbFiles> getPebldsWpfbFiles()    {
        return pebldsWpfbFiles;
    }

    public void setPebldsWpfbFiles(Set<PebldsWpfbFiles> pebldsWpfbFiles)    {
        this.pebldsWpfbFiles = pebldsWpfbFiles;
    }

    @Override
    public OEntity asEntity(EdmEntitySet ees) {
        final List<OProperty<?>> properties = new ArrayList<OProperty<?>>();
        properties.add(OProperties.int32("id", getId()));
        properties.add(OProperties.string("title", getTitle()));
        properties.add(OProperties.string("treaty", getPebldsTreaty().getOdataName()));
        properties.add(OProperties.string("country", getPebldsCountry().getCode()));
        properties.add(OProperties.datetime("submitted", getSubmitted()));

        return OEntities.create(ees, OEntityKey.create(getId()), properties, new ArrayList<OLink>(), null, null);
    }

}
